/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.powerking.pointage.ui;

import com.mysql.jdbc.Connection;
import com.powerking.pointage.lib.AdminDAO;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author delll
 */
public class CalculSalaireJour extends javax.swing.JFrame {

    /**
     * Creates new form CalculSalaireJour
     */
    AdminDAO e = new AdminDAO();
    private Connection cnx;
    public CalculSalaireJour() {
        e.connexion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1ListEmploye = new javax.swing.JComboBox();
        salaireJour = new javax.swing.JTextField();
        jLabel1ChoixEmploye = new javax.swing.JLabel();
        Datejour = new javax.swing.JLabel();
        jLabel2salaireJour = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4PrixHeure = new javax.swing.JLabel();
        jLabel5Prixfixeheure = new javax.swing.JLabel();
        jLabel6fois = new javax.swing.JLabel();
        jLabel7NbrheurePres = new javax.swing.JLabel();
        nbrPresence = new javax.swing.JLabel();
        jButtonExporterSalaire = new javax.swing.JButton();
        jButton1RetoueSalaire = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salaire Journalier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.setName(""); // NOI18N

        jComboBox1ListEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ListEmployeActionPerformed(evt);
            }
        });

        salaireJour.setEditable(false);
        salaireJour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salaireJour.setForeground(new java.awt.Color(255, 0, 51));
        salaireJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaireJourActionPerformed(evt);
            }
        });

        jLabel1ChoixEmploye.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1ChoixEmploye.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1ChoixEmploye.setText("Choisir Un(e)  Employé(e)       :");

        Datejour.setForeground(new java.awt.Color(0, 102, 0));

        jLabel2salaireJour.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2salaireJour.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2salaireJour.setText("Salaire du Jour ");

        jLabel3.setText(" =");

        jLabel4PrixHeure.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4PrixHeure.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4PrixHeure.setText("Prix d'une  heure                   : ");

        jLabel5Prixfixeheure.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5Prixfixeheure.setForeground(new java.awt.Color(102, 51, 255));
        jLabel5Prixfixeheure.setText("3 dt");

        jLabel6fois.setText("*");

        jLabel7NbrheurePres.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7NbrheurePres.setForeground(new java.awt.Color(153, 102, 0));
        jLabel7NbrheurePres.setText("Nombre d'heures de présence : ");

        nbrPresence.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nbrPresence.setForeground(new java.awt.Color(255, 0, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2salaireJour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Datejour, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4PrixHeure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1ChoixEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(122, 122, 122)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1ListEmploye, 0, 106, Short.MAX_VALUE)
                        .addComponent(salaireJour))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6fois, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5Prixfixeheure, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7NbrheurePres)
                .addGap(171, 171, 171)
                .addComponent(nbrPresence, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1ChoixEmploye)
                    .addComponent(jComboBox1ListEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5Prixfixeheure)
                    .addComponent(jLabel4PrixHeure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6fois, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7NbrheurePres)
                    .addComponent(nbrPresence, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaireJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addComponent(jLabel2salaireJour))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Datejour, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButtonExporterSalaire.setBackground(new java.awt.Color(204, 204, 204));
        jButtonExporterSalaire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonExporterSalaire.setText("Exporter Salaire");
        jButtonExporterSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExporterSalaireActionPerformed(evt);
            }
        });

        jButton1RetoueSalaire.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1RetoueSalaire.setText("Retour");
        jButton1RetoueSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RetoueSalaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButtonExporterSalaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1RetoueSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExporterSalaire)
                    .addComponent(jButton1RetoueSalaire))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ListEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ListEmployeActionPerformed

        if (jComboBox1ListEmploye.getSelectedIndex()!=-1){
            String[] data = jComboBox1ListEmploye.getSelectedItem().toString().split(";");
            int mat = Integer.parseInt(data[1]);
           // try {
                // TODO add your handling code here:
               
                ResultSet rs = e.calculsalaireJour(mat);    
           // } 
            //catch (SQLException ex) {
             //   Logger.getLogger(CalculSalaireJour.class.getName()).log(Level.SEVERE, null, ex);
           // }
            
        }
    }//GEN-LAST:event_jComboBox1ListEmployeActionPerformed

    private void salaireJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaireJourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaireJourActionPerformed

    private void jButton1RetoueSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RetoueSalaireActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1RetoueSalaireActionPerformed

    private void jButtonExporterSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExporterSalaireActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            e.connexion();
            e.exportCSV();
        } catch (IOException ex) {
            Logger.getLogger(Historique.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonExporterSalaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculSalaireJour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculSalaireJour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculSalaireJour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculSalaireJour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculSalaireJour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Datejour;
    private javax.swing.JButton jButton1RetoueSalaire;
    private javax.swing.JButton jButtonExporterSalaire;
    private javax.swing.JComboBox jComboBox1ListEmploye;
    private javax.swing.JLabel jLabel1ChoixEmploye;
    private javax.swing.JLabel jLabel2salaireJour;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4PrixHeure;
    private javax.swing.JLabel jLabel5Prixfixeheure;
    private javax.swing.JLabel jLabel6fois;
    private javax.swing.JLabel jLabel7NbrheurePres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nbrPresence;
    private javax.swing.JTextField salaireJour;
    // End of variables declaration//GEN-END:variables
}
