/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.powerking.pointage.ui;

import com.powerking.pointage.lib.AdminDAO;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author delll
 */
public class SalaireCalcule extends javax.swing.JFrame {

    /**
     * Creates new form SalaireCalcule
     */
     AdminDAO e= new AdminDAO();
        private Connection cnx;
        private int mat;

    public SalaireCalcule() {
        e.connexion();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("gestion_pointage?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        employeQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM Employe e");
        employeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : employeQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxListEmploye = new javax.swing.JComboBox();
        salaireJour = new javax.swing.JTextField();
        jLabel1choisirEmploye = new javax.swing.JLabel();
        jour = new javax.swing.JLabel();
        jLabel2salaireJour = new javax.swing.JLabel();
        jLabel3Egal = new javax.swing.JLabel();
        jLabel4prixheure = new javax.swing.JLabel();
        jLabelPrixHeure = new javax.swing.JLabel();
        jLabel6fois = new javax.swing.JLabel();
        jLabel7nbrHeurePres = new javax.swing.JLabel();
        nbrHeurePresence = new javax.swing.JLabel();
        jButton1retourSal = new javax.swing.JButton();
        jButtonExporterSalaire = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salaire Journalier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.setName(""); // NOI18N

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, employeList, jComboBoxListEmploye);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxListEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxListEmployeActionPerformed(evt);
            }
        });

        salaireJour.setEditable(false);
        salaireJour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salaireJour.setForeground(new java.awt.Color(255, 0, 51));
        salaireJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaireJourActionPerformed(evt);
            }
        });

        jLabel1choisirEmploye.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1choisirEmploye.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1choisirEmploye.setText("Choisir Un(e)  Employé(e)       :");

        jour.setForeground(new java.awt.Color(0, 102, 0));

        jLabel2salaireJour.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2salaireJour.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2salaireJour.setText("Salaire du Jour ");

        jLabel3Egal.setText(" =");

        jLabel4prixheure.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4prixheure.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4prixheure.setText("Prix d'une  heure                   : ");

        jLabelPrixHeure.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelPrixHeure.setForeground(new java.awt.Color(102, 51, 255));
        jLabelPrixHeure.setText("3 dt");

        jLabel6fois.setText("*");

        jLabel7nbrHeurePres.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7nbrHeurePres.setForeground(new java.awt.Color(153, 102, 0));
        jLabel7nbrHeurePres.setText("Nombre d'heures de présence : ");

        nbrHeurePresence.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nbrHeurePresence.setForeground(new java.awt.Color(255, 0, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2salaireJour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3Egal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4prixheure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1choisirEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(122, 122, 122)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxListEmploye, 0, 106, Short.MAX_VALUE)
                        .addComponent(salaireJour))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6fois, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelPrixHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7nbrHeurePres)
                .addGap(171, 171, 171)
                .addComponent(nbrHeurePresence, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1choisirEmploye)
                    .addComponent(jComboBoxListEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrixHeure)
                    .addComponent(jLabel4prixheure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6fois, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7nbrHeurePres)
                    .addComponent(nbrHeurePresence, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaireJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3Egal))
                        .addComponent(jLabel2salaireJour))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jButton1retourSal.setBackground(new java.awt.Color(204, 204, 204));
        jButton1retourSal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1retourSal.setText("Retour");
        jButton1retourSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1retourSalActionPerformed(evt);
            }
        });

        jButtonExporterSalaire.setBackground(new java.awt.Color(204, 204, 204));
        jButtonExporterSalaire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonExporterSalaire.setText("Exporter Salaire");
        jButtonExporterSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExporterSalaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1retourSal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExporterSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExporterSalaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1retourSal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxListEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxListEmployeActionPerformed

    if (jComboBoxListEmploye.getSelectedIndex()!=1){
            String[] data = jComboBoxListEmploye.getSelectedItem().toString().split(";");
            int mat = Integer.parseInt(data[1]);
            try {
                // TODO add your handling code here:
                String req = "SELECT salaire_jour, date, taux_pre FROM employe e , pointage p WHERE p.matricule = e.matricule AND p.matricule = "+mat;
                Statement s = cnx.createStatement();
                ResultSet rs = s.executeQuery(req);

                while (rs.next()){
                    jLabelPrixHeure.setText(rs.getString(1)+" dt");
                    jour.setText(rs.getString(2));
                    nbrHeurePresence.setText(rs.getInt(3)+"");
                }
            } catch (SQLException ex) {
                Logger.getLogger(SalaireCalcule.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_jComboBoxListEmployeActionPerformed

    private void salaireJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaireJourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaireJourActionPerformed

    private void jButton1retourSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1retourSalActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1retourSalActionPerformed

    private void jButtonExporterSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExporterSalaireActionPerformed
        try {
            // TODO add your handling code here:
            AdminDAO.exportCSVsalaireJour(cnx);
        } catch (IOException ex) {
            Logger.getLogger(SalaireCalcule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonExporterSalaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaireCalcule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaireCalcule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaireCalcule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaireCalcule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaireCalcule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<com.powerking.pointage.lib.ClassEmploye> employeList;
    private javax.persistence.Query employeQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1retourSal;
    private javax.swing.JButton jButtonExporterSalaire;
    private javax.swing.JComboBox jComboBoxListEmploye;
    private javax.swing.JLabel jLabel1choisirEmploye;
    private javax.swing.JLabel jLabel2salaireJour;
    private javax.swing.JLabel jLabel3Egal;
    private javax.swing.JLabel jLabel4prixheure;
    private javax.swing.JLabel jLabel6fois;
    private javax.swing.JLabel jLabel7nbrHeurePres;
    private javax.swing.JLabel jLabelPrixHeure;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jour;
    private javax.swing.JLabel nbrHeurePresence;
    private javax.swing.JTextField salaireJour;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
